### ISSUE TITLE
dump of xiaomi 11 lite 5g ne found DT_ERR_NOTFOUND

### ISSUE THREAD

**Issue by 99degree** [msm8916-mainline/linux-mdss-dsi-panel-driver-generator#21]
fdt dump of /sys/firmware/fdt
[lisa_fdt_dump.zip](https://github.com/msm8916-mainline/linux-mdss-dsi-panel-driver-generator/files/9111997/lisa_fdt_dump.zip)
:~/source/linux-mdss-dsi-panel-driver-generator# ./lmdpdg.py ../Android_boot_image_editor/build/lisa_dtbo/dt/fdt
Parsing: ../Android_boot_image_editor/build/lisa_dtbo/dt/fdt
ERROR: Failed to get property: qcom,dsi-panel
Traceback (most recent call last):
  File "./lmdpdg.py", line 75, in <module>
    for offset in Panel.find(fdt):
  File "/root/source/linux-mdss-dsi-panel-driver-generator/panel.py", line 333, in find
    panel_phandles.add(fdt.getprop(display, 'qcom,dsi-panel').as_uint32())
  File "/root/source/linux-mdss-dsi-panel-driver-generator/fdt2.py", line 32, in getprop
    return super().getprop(nodeoffset, prop_name, quiet)
  File "/usr/local/lib/python3.8/dist-packages/libfdt.py", line 451, in getprop
    pdata = check_err_null(fdt_getprop(self._fdt, nodeoffset, prop_name),
  File "/usr/local/lib/python3.8/dist-packages/libfdt.py", line 156, in check_err_null
    raise FdtException(val)
libfdt.FdtException: pylibfdt error -1: FDT_ERR_NOTFOUND

**Comment by stephan-gh** [comment]
Probably related to #19, maybe @z3ntu can finish that up. :)

**Comment by stephan-gh** [comment]
@99degree Can you try if the updated PR fixes your problem?

**Comment by 99degree** [comment]
some more progress:

root@LAPTOP:~/source/linux-mdss-dsi-panel-driver-generator# git diff
diff --git a/panel.py b/panel.py
index bb6b793..0301170 100644
--- a/panel.py
+++ b/panel.py
@@ -322,6 +322,12 @@ def find(fdt: Fdt2) -> Iterator[int]:
                        for sub in fdt.subnodes(mdp):
                                yield sub

+               for mdp in fdt.find_by_compatible('qcom,sde-kms'):
+                       for sub in fdt.subnodes(mdp):
+                               panel = Panel.parse(fdt, sub)
+                               if panel:
+                                       yield panel
+
                # Newer device trees do not necessarily have panels below MDP,
                # search for qcom,dsi-display node instead
                panel_phandles = set()
root@LAPTOP:~/source/linux-mdss-dsi-panel-driver-generator# ./lmdpdg.py ../dts/lisa_fdt_dump.dtb
Parsing: ../dts/lisa_fdt_dump.dtb
Parsing: nt36672e_fhd_plus_144_video (nt36672e fhd plus 144Hz video panel)
ERROR: Failed to get property: qcom,mdss-dsi-panel-name
Traceback (most recent call last):
  File "./lmdpdg.py", line 77, in <module>
    panel = Panel.parse(fdt, offset)
  File "/root/source/linux-mdss-dsi-panel-driver-generator/panel.py", line 316, in parse
    name = fdt.getprop_or_none(node, 'qcom,mdss-dsi-panel-name')
  File "/root/source/linux-mdss-dsi-panel-driver-generator/fdt2.py", line 38, in getprop_or_none
    prop = self.getprop(nodeoffset, prop_name, [FDT_ERR_NOTFOUND])
  File "/root/source/linux-mdss-dsi-panel-driver-generator/fdt2.py", line 32, in getprop
    return super().getprop(nodeoffset, prop_name, quiet)
  File "/usr/local/lib/python3.8/dist-packages/libfdt.py", line 451, in getprop
    pdata = check_err_null(fdt_getprop(self._fdt, nodeoffset, prop_name),
  File "/usr/local/lib/python3.8/dist-packages/libfdt.py", line 1276, in fdt_getprop
    return _libfdt.fdt_getprop(fdt, nodeoffset, name)
TypeError: in method 'fdt_getprop', argument 2 of type 'int'
Parsing: nt36672e_fhd_plus_120_video (nt36672e fhd plus 120Hz Video panel)
ERROR: Failed to get property: qcom,mdss-dsi-panel-name
Traceback (most recent call last):
  File "./lmdpdg.py", line 77, in <module>
    panel = Panel.parse(fdt, offset)
  File "/root/source/linux-mdss-dsi-panel-driver-generator/panel.py", line 316, in parse
    name = fdt.getprop_or_none(node, 'qcom,mdss-dsi-panel-name')
  File "/root/source/linux-mdss-dsi-panel-driver-generator/fdt2.py", line 38, in getprop_or_none
    prop = self.getprop(nodeoffset, prop_name, [FDT_ERR_NOTFOUND])
  File "/root/source/linux-mdss-dsi-panel-driver-generator/fdt2.py", line 32, in getprop
    return super().getprop(nodeoffset, prop_name, quiet)
  File "/usr/local/lib/python3.8/dist-packages/libfdt.py", line 451, in getprop
    pdata = check_err_null(fdt_getprop(self._fdt, nodeoffset, prop_name),
  File "/usr/local/lib/python3.8/dist-packages/libfdt.py", line 1276, in fdt_getprop
    return _libfdt.fdt_getprop(fdt, nodeoffset, name)
TypeError: in method 'fdt_getprop', argument 2 of type 'int'
Parsing: nt36672e_fhd_plus_90hz_video (nt36672e 90Hz fhd plus video mode panel with DSC)
ERROR: Failed to get property: qcom,mdss-dsi-panel-name
Traceback (most recent call last):
  File "./lmdpdg.py", line 77, in <module>
    panel = Panel.parse(fdt, offset)
  File "/root/source/linux-mdss-dsi-panel-driver-generator/panel.py", line 316, in parse
    name = fdt.getprop_or_none(node, 'qcom,mdss-dsi-panel-name')
  File "/root/source/linux-mdss-dsi-panel-driver-generator/fdt2.py", line 38, in getprop_or_none
    prop = self.getprop(nodeoffset, prop_name, [FDT_ERR_NOTFOUND])
  File "/root/source/linux-mdss-dsi-panel-driver-generator/fdt2.py", line 32, in getprop
    return super().getprop(nodeoffset, prop_name, quiet)
  File "/usr/local/lib/python3.8/dist-packages/libfdt.py", line 451, in getprop
    pdata = check_err_null(fdt_getprop(self._fdt, nodeoffset, prop_name),
  File "/usr/local/lib/python3.8/dist-packages/libfdt.py", line 1276, in fdt_getprop
    return _libfdt.fdt_getprop(fdt, nodeoffset, name)
TypeError: in method 'fdt_getprop', argument 2 of type 'int'
Parsing: nt36672e_fhd_plus_60_video (nt36672e 60 Hz fhd plus video mode panel without DSC)
ERROR: Failed to get property: qcom,mdss-dsi-off-command-state
Traceback (most recent call last):
  File "./lmdpdg.py", line 75, in <module>
    for offset in Panel.find(fdt):
  File "/root/source/linux-mdss-dsi-panel-driver-generator/panel.py", line 327, in find
    panel = Panel.parse(fdt, sub)
  File "/root/source/linux-mdss-dsi-panel-driver-generator/panel.py", line 317, in parse
    return name and Panel(name.as_str(), fdt, node)
  File "/root/source/linux-mdss-dsi-panel-driver-generator/panel.py", line 269, in __init__
    'off': CommandSequence(fdt, mode_node, 'off')
  File "/root/source/linux-mdss-dsi-panel-driver-generator/panel.py", line 139, in __init__
    self.state = CommandSequence.State(fdt.getprop(node, f'qcom,mdss-dsi-{cmd}-command-state').as_str())
  File "/root/source/linux-mdss-dsi-panel-driver-generator/fdt2.py", line 32, in getprop
    return super().getprop(nodeoffset, prop_name, quiet)
  File "/usr/local/lib/python3.8/dist-packages/libfdt.py", line 451, in getprop
    pdata = check_err_null(fdt_getprop(self._fdt, nodeoffset, prop_name),
  File "/usr/local/lib/python3.8/dist-packages/libfdt.py", line 156, in check_err_null
    raise FdtException(val)
libfdt.FdtException: pylibfdt error -1: FDT_ERR_NOTFOUND
root@LAPTOP:~/source/linux-mdss-dsi-panel-driver-generator#

**Comment by stephan-gh** [comment]
I think this was fixed with @z3ntu's PR?
